language: perl

perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

# disable dependency install
install:
  - true

script:
  - ./bootstrap
  - ./configure --prefix=$HOME/lxadm
  - make install
